# Generated by Django 5.2.7 on 2025-11-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_points',
            field=models.IntegerField(blank=True, help_text='Activity points awarded for participation (only for Activity Points events)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Event'), ('ACTIVITY_POINTS', 'Event with Activity Points')], default='NORMAL', max_length=20),
        ),
    ]
