# Generated by Django 5.2.7 on 2025-11-02 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='total_activity_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(help_text='University Seat Number (must contain both letters and numbers)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='USN must contain both letters and numbers (e.g., 1AB20CS001)', regex='^(?=.*[A-Za-z])(?=.*[0-9])[A-Za-z0-9]+$')]),
        ),
    ]
