# Generated by Django 5.2.7 on 2025-11-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_activity_points'),
        ('students', '0002_student_total_activity_points_alter_student_usn'),
    ]

    operations = [
    ]
