# Generated by Django 5.2.7 on 2025-11-13 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_activity_points_event_event_type'),
        ('students', '0003_merge_20251102_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='social_score',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Social score percentage (100.00 by default)', max_digits=5),
        ),
        migrations.CreateModel(
            name='SocialScoreLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('change_amount', models.DecimalField(decimal_places=2, help_text='Positive for increase, negative for decrease', max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.CharField(choices=[('ABSENT_FROM_EVENT', 'Marked Absent from Event'), ('PRESENT_AT_NON_ACTIVITY_EVENT', 'Present at Non-Activity Event'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_score_changes', to='events.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_score_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Social Score Log',
                'verbose_name_plural': 'Social Score Logs',
                'db_table': 'social_score_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
