# Generated by Django 5.2.7 on 2025-10-29 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Faculty code must be alphanumeric', regex='^[A-Za-z0-9]+$')])),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits', regex='^\\+?1?\\d{9,15}$')])),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
                'db_table': 'faculty',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
