# Generated by Django 5.2.7 on 2025-10-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('can_create_events', models.BooleanField(default=False)),
                ('can_edit_events', models.BooleanField(default=False)),
                ('can_delete_events', models.BooleanField(default=False)),
                ('can_start_events', models.BooleanField(default=False)),
                ('can_end_events', models.BooleanField(default=False)),
                ('can_mark_attendance', models.BooleanField(default=False)),
                ('can_add_members', models.BooleanField(default=False)),
                ('can_remove_members', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Club Role',
                'verbose_name_plural': 'Club Roles',
                'db_table': 'club_roles',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100, unique=True)),
                ('club_description', models.TextField(blank=True, null=True)),
                ('club_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('club_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_clubs', to='students.student')),
                ('faculty_incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
                'db_table': 'clubs',
                'ordering': ['club_name'],
            },
        ),
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_login_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('club_password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_members', to='clubs.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to='students.student')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='clubs.clubrole')),
            ],
            options={
                'verbose_name': 'Club Member',
                'verbose_name_plural': 'Club Members',
                'db_table': 'club_members',
                'ordering': ['club', '-joined_date'],
                'unique_together': {('club', 'student')},
            },
        ),
    ]
