# Generated by Django 5.2.7 on 2025-10-29 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('events', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_registered', models.IntegerField(default=0)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('report_generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_sent_to', models.CharField(blank=True, max_length=255, null=True)),
                ('report_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Report',
                'verbose_name_plural': 'Event Reports',
                'db_table': 'event_reports',
                'ordering': ['-report_generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], max_length=20)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='events.event')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to='clubs.clubmember')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance',
                'ordering': ['-marked_at'],
                'unique_together': {('event', 'student')},
            },
        ),
    ]
